# Generated by Django 4.1.4 on 2023-01-08 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_questions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questions',
            old_name='features',
            new_name='WhichLand',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='clicked',
        ),
    ]
